---
- name: using loops concept
  hosts: all 
  tasks: 
   - name: using loops install or uninstall or updated on softwares
     apt:
       name: "{{item.a}}"
       state: "{{item.b}}"
       update_cache: "{{item.c}}"
     loop:
      - {a: tree,b: absent,c: no}
      - {a: git,b: present,c: yes}
      - {a: maven,b: present,c: yes}
...      
